plugins {
    id 'com.android.application' version '8.4.2' apply true
}

android {
    namespace 'com.example.androidplaceholder'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.androidplaceholder"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "0.0.1"
    }

    buildTypes {
        release { minifyEnabled false }
        debug { }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
